name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Test-and-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Rust build
        run: make
